{% set name = "reportlab" %}
{% set version = "4.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 41e8287af965e5996764933f3e75e7f363c3b6f252ba172f9429e81658d7b170

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python
    - pillow >=9.0.0
    - charset-normalizer
  run_constrained:
    - rl-accel >=0.9.0,<1.1
    - rlpycairo >=0.2.0,<1
    - freetype-py >=2.3.0,<2.4
    - rl-renderpm >=4.0.3,<4.1

test:
  source_files:
    - tests
    - docs
    - tools
    - setup.py
  imports:
    - reportlab
    - reportlab.graphics.charts
    - reportlab.graphics.samples
    - reportlab.graphics.widgets
    - reportlab.graphics.barcode
    - reportlab.graphics
    - reportlab.lib
    - reportlab.pdfbase
    - reportlab.pdfgen
    - reportlab.platypus
  requires:
    - pip
  commands:
    - pip check
    - python setup.py tests  # [unix]
    - python setup.py tests --verbose-tests --no-download-t1-files --exclude=test_pdfgen_general --exclude=test_pdfgen_callback  # [win]

about:
  home: https://docs.reportlab.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The Reportlab Toolkit
  description: |
    The ReportLab Toolkit. An Open Source Python library for generating PDFs and graphics.
  doc_url: https://docs.reportlab.com
  dev_url: https://hg.reportlab.com/hg-public/reportlab

extra:
  recipe-maintainers:
    - mcs07
