{% set name = "reportlab" %}
{% set version = "3.6.12" %}
{% set sha256 = "b13cebf4e397bba14542bcd023338b6ff2c151a3a12aabca89eecbf972cb361a" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<37]
  script: {{PYTHON}} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - pip
    - wheel
    - freetype 2.10.4
  run:
    - python
    - pillow >=9.0.0
    - freetype 2.10.4,<3.0a0

test:
  imports:
    - reportlab
    - reportlab.graphics.charts
    - reportlab.graphics.samples
    - reportlab.graphics.widgets
    - reportlab.graphics.barcode
    - reportlab.graphics
    - reportlab.lib
    - reportlab.pdfbase
    - reportlab.pdfgen
    - reportlab.platypus
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://docs.reportlab.com/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: The Reportlab Toolkit
  description: |
    The ReportLab Toolkit. An Open Source Python library for generating PDFs and graphics.
  doc_url: https://docs.reportlab.com/
  dev_url: https://github.com/MrBitBucket/reportlab-mirror

extra:
  recipe-maintainers:
    - mcs07
