{% set name = "reportlab" %}
{% set version = "4.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/reportlab-{{ version }}.tar.gz
  sha256: 073b0975dab69536acd3251858e6b0524ed3e087e71f1d0d1895acb50acf9c7b


build:
  number: 0
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools
    - pip
    - wheel
    - charset-normalizer 3.3.2 # Need for tests
    - pillow >=9 # Need for tests
  run:
    - python
    - pillow
    - charset-normalizer

test:
  imports:
    - reportlab
    - reportlab.graphics.charts
    - reportlab.graphics.samples
    - reportlab.graphics.widgets
    - reportlab.graphics.barcode
    - reportlab.graphics
    - reportlab.lib
    - reportlab.pdfbase
    - reportlab.pdfgen
    - reportlab.platypus
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://docs.reportlab.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The Reportlab Toolkit
  description: |
    The ReportLab Toolkit. An Open Source Python library for generating PDFs and graphics.
  doc_url: https://docs.reportlab.com
  dev_url: https://hg.reportlab.com/hg-public/reportlab

extra:
  recipe-maintainers:
    - mcs07
