travis:
  secure:
    BINSTAR_TOKEN: Q2KiSY+uJWvMeiMDO5Y7eT/3rRkE0eQOZGCLZ+RoVJp03CJdWGpToJcKsXRfDePg4ccW//Jhgc2g3X5on3IwewsubGiTpmxX4dWU5sqEQsa0okfsbablgIRhi1LOl4Y+Bd6yxkespom++n0/+8nZr5PlM+ZZ7HJzwQBHcH8HRK6Lv8ZiHYaf+n2bQWaQmVYZDH/iarkxyLhSGjy4/nnr4NTHDeFfiZdbiQyOMHqOh6hyD1KARXgJpDz7CvzjiXyME2DOM9Ytayg874bdIE+Zym7kJRbgde3IL1wogCicb5Pndwrd26pX0A4rwBhhOv6XQkshj6TclKDL9sJNDvyC1SuT4PtnK/NcfcsRoI1XDnCgcAokaLfnNA6dWp+TqWJmhTo1ohTCUl4jhCi6vAqN2T7HztQJQmC/LrTHS3HNMEAs/Xo4Lt4iqxsK5LbZ/8fz//N69l/gfF2Y6/2zD9nzF2F/CmqWyWtTOyMnEtio3OkUaBSphFEgH6aHaC/0CRopRepXDifoGigPp4V0ePi4jCpjkkO0GDFWKSkk0C3f0jAT90OsBSQ/19Vvan5fSHUmdVCNMKeRTyrvjIpS4Qfe9CtUwBQ4NGo+Rh4Wa3lt4ilWbbpOiIJd37kTL9euGWoYaLHNjYu3TO9wa9/eTovQs3WkMzSg3MbgBHx9jEx3tVo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
